# Generated by Django 6.0 on 2025-12-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reminder',
            new_name='Schedule',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='reminder',
            new_name='schedule',
        ),
    ]
