# Generated by Django 6.0 on 2025-12-19 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0002_rename_reminder_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_of_day',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default='morning', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='drugapp.medication'),
        ),
    ]
