# Generated by Django 6.0 on 2026-01-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dose_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_of_day',
            field=models.CharField(choices=[('8am', '8 AM'), ('12noon', '12 Noon'), ('6pm', '6 PM')], max_length=10),
        ),
    ]
