# Generated by Django 6.0 on 2026-01-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0005_medication_dose_time_alter_schedule_time_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='adherence',
            field=models.CharField(choices=[('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
