# Generated by Django 6.0 on 2026-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0006_notification_adherence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_of_day',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='adherence',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken'), ('MISSED', 'Missed')], default='PENDING', max_length=20),
        ),
    ]
