# Generated by Django 6.0 on 2026-01-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0007_remove_schedule_is_sent_remove_schedule_time_of_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
